namespace DiscordBot.Core;

public class StockSummary
{
    public string Symbol;
    public string Name;
    public string Description;
    public string Sector;
    public decimal Price;
    public decimal Eps;
    public decimal AnalystPriceTarget;

    public StockSummary(
        string symbol,
        string name,
        string description,
        string sector,
        decimal price,
        decimal eps,
        decimal priceTarget
    )
    {
        Symbol = symbol;
        Name = name;
        Description = description;
        Sector = sector;
        Price = price;
        Eps = eps;
        AnalystPriceTarget = priceTarget;
    }
}



//{
//    "Symbol": "IBM",
//    "AssetType": "Common Stock",
//    "Name": "International Business Machines",
//    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
//    "CIK": "51143",
//    "Exchange": "NYSE",
//    "Currency": "USD",
//    "Country": "USA",
//    "Sector": "TECHNOLOGY",
//    "Industry": "COMPUTER & OFFICE EQUIPMENT",
//    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
//    "OfficialSite": "https://www.ibm.com",
//    "FiscalYearEnd": "December",
//    "LatestQuarter": "2024-12-31",
//    "MarketCapitalization": "238808203000",
//    "EBITDA": "14676000000",
//    "PERatio": "40.14",
//    "PEGRatio": "8.54",
//    "BookValue": "26.44",
//    "DividendPerShare": "0",
//    "DividendYield": "0.0292",
//    "EPS": "6.37",
//    "RevenuePerShareTTM": "68.11",
//    "ProfitMargin": "0.102",
//    "OperatingMarginTTM": "0.141",
//    "ReturnOnAssetsTTM": "0.0473",
//    "ReturnOnEquityTTM": "0.267",
//    "RevenueTTM": "62579999000",
//    "GrossProfitTTM": "35378999000",
//    "DilutedEPSTTM": "6.37",
//    "QuarterlyEarningsGrowthYOY": "0.141",
//    "QuarterlyRevenueGrowthYOY": "0.015",
//    "AnalystTargetPrice": "239.09",
//    "AnalystRatingStrongBuy": "2",
//    "AnalystRatingBuy": "5",
//    "AnalystRatingHold": "8",
//    "AnalystRatingSell": "3",
//    "AnalystRatingStrongSell": "1",
//    "TrailingPE": "40.14",
//    "ForwardPE": "23.92",
//    "PriceToSalesRatioTTM": "3.816",
//    "PriceToBookRatio": "8.66",
//    "EVToRevenue": "4.466",
//    "EVToEBITDA": "23.02",
//    "Beta": "0.71",
//    "52WeekHigh": "261.8",
//    "52WeekLow": "158.38",
//    "50DayMovingAverage": "224.8",
//    "200DayMovingAverage": "200.69",
//    "SharesOutstanding": "924645000",
//    "DividendDate": "2024-12-10",
//    "ExDividendDate": "2025-02-10"
//}
